---
- name: Install brave-browser
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Download Brave archive keyring
      ansible.builtin.get_url:
        url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
        dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"


    - name: Add apt source list for Brave
      ansible.builtin.lineinfile:
        state: "present"
        create: true
        line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        path: "/etc/apt/sources.list.d/brave-browser-release.list"

    - name: Install brave-browser
      ansible.builtin.apt:
        update_cache: true
        state: latest
        name: brave-browser
