---
- name: Playbook to install and configure the desktop environment
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Installs sway and related applications
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        name:
          - mako-notifier
          - sakura
          - sway
          - swayidle
          - swaylock
          - waybar
          - wofi

    - name: Installs audio and video applications
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        name:
          - mpv
          - imv

    - name: Clean apt cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true
