---
- name: Install and configure the desktop environment
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Installs sway and related applications
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        name:
          - brightnessctl
          - mako-notifier
          - sakura
          - sway
          - swayidle
          - swaylock
          - waybar
          - wofi

    - name: Installs audio and video applications
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        name:
          - mpv
          - imv

    - name: Clean apt cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true

- name: Copy configuration files for desktop applications
  hosts: localhost
  connection: local
  tasks:
    - name: Copy sway configuration files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../config/sway/"
        dest: "/home/{{ ansible_user_id }}/.config/sway/"
        mode: '0754'

    - name: Make sway scripts executable
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: '0754'
      with_fileglob:
        - "/home/{{ ansible_user_id }}/.config/sway/scripts/*"

    - name: Copy swaylock configuration files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../config/swaylock/"
        dest: "/home/{{ ansible_user_id }}/.config/swaylock/"
        mode: '0754'

    - name: Copy waybar configuration files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../config/waybar/"
        dest: "/home/{{ ansible_user_id }}/.config/waybar/"
        mode: '0754'

    - name: Make waybar scripts executable
      ansible.builtin.file:
        dest: "/home/{{ ansible_user_id }}/.config/waybar/start.sh"
        mode: '0754'

    - name: Copy wofi configuration files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../config/wofi/"
        dest: "/home/{{ ansible_user_id }}/.config/wofi/"
        mode: '0754'
