---
- name: Install development packages
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install development related applications via apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        name:
          - neovim

    - name: Install pynvim via pip
      ansible.builtin.pip:
        name: pynvim
        state: latest
        umask: "0022"
        extra_args: "--break-system-packages"

- name: Copy configuration files for development applications
  hosts: localhost
  connection: local
  tasks:
    - name: Copy neovim configuration files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../config/nvim"
        dest: "/home/{{ ansible_user_id }}/.config/nvim"
        mode: '0744'

    - name: Install python black via pipx
      community.general.pipx:
        name: black
        state: latest

    - name: Install tox via pipx
      community.general.pipx:
        name: tox
        state: latest
