---
- name: Install system packages
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install system applications
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        name:
          - pipx
          - python3
          - python3-pip
          - python-is-python3
          - fish
          - fd-find
          - ripgrep
          - bat
          - pulseaudio-utils
